server:
  port: 8088
debug: true
logging:
  level:
    com:
      redisCache: debug
    root: debug
spring:
  cache:
    type: redis
  datasource:
    dynamic:
      # druid连接池设置
      druid:
        # 配置初始化大小、最小、最大线程数
        initialSize: 5
        minIdle: 5
        # CPU核数+1，也可以大些但不要超过20，数据库加锁时连接过多性能下降
        maxActive: 20
        # 最大等待时间，内网：800，外网：1200（三次握手1s）
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最大空间时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1
        testWhileIdle: true
        # 设置从连接池获取连接时是否检查连接有效性，true检查，false不检查
        testOnBorrow: true
        # 设置从连接池归还连接时是否检查连接有效性，true检查，false不检查
        testOnReturn: true
        # 可以支持PSCache（提升写入、查询效率）
        poolPreparedStatements: true
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
        # 保持长连接
        keepAlive: true
        maxPoolPreparedStatementPerConnectionSize: 20
        useGlobalDataSourceStat: true
        web-stat-filter:
          # 是否启用StatFilter默认值true
          enabled: true
          # 添加过滤规则
          url-pattern: /*
          # 忽略过滤的格式
          exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico
        stat-view-servlet:
          # 是否启用StatViewServlet默认值true
          enabled: true
          # 访问路径为/druid时，跳转到StatViewServlet
          url-pattern: /druid/*
          # 是否能够重置数据
          reset-enable: false
          # 需要账号密码才能访问控制台，默认为root
          login-username: druid
          login-password: druid
          # IP白名单
          allow: 127.0.0.1
          # IP黑名单（共同存在时，deny优先于allow）
          deny:
      #  dynamic主从设置
      # 设置默认的数据源或者数据源组,默认值即为 bi
      primary: bi
      # 设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.
      strict: false
      datasource:
        base:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: ENC(N56kOIPLh4b83vHP3OaNNJ0MOza88UTaHWgjgo/JYVlHQhpUKypQZmA/axBFkgr7K4zKjhaCpZFiLlWnoQCYLFuFh9uCO/WZZTlHYn8boIOBPougbwDe9rk6gsgmXUmHWkr8dWL73yDAEXX3k/HPp46T2007pZC3EbUJHSiehKXxOAfmEwuoFG4GaFZd6ySKiz3tX9ua/RzH4e6SQ5SSWg==)
          username: ENC(J132ZzOCyDODOtumOyJIHBScakzXwhV8ENt74gvYu1rnmR6SpKCRvps0czEwPkWR)
          password: ENC(++FZHFS1Ad6tJ/VfJ6srAfq8jj7biiuoOGW6M/fJKFH8Fupaj0ZWI7PAln/jKuCb)
          type: com.alibaba.druid.pool.DruidDataSource
        bi:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: ENC(mIhL1RL0CvdSqu0QfAQKH3MeHCBej8XbcWYvPpNuWh5yLU+5z2I2zXf7wezfp7MDc56uJAzRVKViWlXOpTAtbsMLrCTEKEioZiyY747k8Cw514DKggNu5vUN+dPYm3MpkNz1QQ63oSMzXJ6rYoGck4HQ3dJ96HPRHh7xc3dsm40c6dbsTP+rX5rgNQu8+/d9PknNgriSi4aNdDxy1iz5gg==)
          username: ENC(tp/CXqcyiL9QFGas0Ukt9/Gn8HC9j8JV2510Q9qPvAs09BRvDptxVLhufsnBx9ol)
          password: ENC(Z243l8alfYi3Xr0amhRS8CVoo08YS2BvdpUM+3QD0ilQsJj51hXnUfk3s+TtEibc)
          type: com.alibaba.druid.pool.DruidDataSource
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      connect-timeout: 10000


