spring:
  cache:
    type: redis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(ni2p4AWoXBxxw6ZdagKFnFurkNIwbNAdroOiVb/Yma92uwrpr4zfbQFDCFXE2chP5GNOc7oLN1VXGKVOT1QEY84cVw9PulvomntjBqF3err3yn+hjUiYSdge01hxQ0g0Zd3mpukzedM2faAO4wQmxle1Ir7ltifDDhlA67a23SZqtUp8oBwewjVGccaiernGYqiGFoBljypINiEbCcrXMQ==)
    username: ENC(JVNZz2OxsxfvsQPRMJMgpcyGhFfN8VmEk05tviV33EE2mtMQ57BWmxiPtluhNkLX)
    password: ENC(CYo8RiOR0+NszQJtVLFyR0dqoI9fVyGjEHIlLy3VGM8X98ahVHj5l1WhbubNf9D0)
#    url: ENC(N56kOIPLh4b83vHP3OaNNJ0MOza88UTaHWgjgo/JYVlHQhpUKypQZmA/axBFkgr7K4zKjhaCpZFiLlWnoQCYLFuFh9uCO/WZZTlHYn8boIOBPougbwDe9rk6gsgmXUmHWkr8dWL73yDAEXX3k/HPp46T2007pZC3EbUJHSiehKXxOAfmEwuoFG4GaFZd6ySKiz3tX9ua/RzH4e6SQ5SSWg==)
#    username: ENC(J132ZzOCyDODOtumOyJIHBScakzXwhV8ENt74gvYu1rnmR6SpKCRvps0czEwPkWR)
#    password: ENC(++FZHFS1Ad6tJ/VfJ6srAfq8jj7biiuoOGW6M/fJKFH8Fupaj0ZWI7PAln/jKuCb)
    type: com.alibaba.druid.pool.DruidDataSource
    # druid连接池设置
    druid:
      # 配置初始化大小、最小、最大线程数
      initialSize: 5
      minIdle: 5
      # CPU核数+1，也可以大些但不要超过20，数据库加锁时连接过多性能下降
      maxActive: 20
      # 最大等待时间，内网：800，外网：1200（三次握手1s）
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最大空间时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      # 设置从连接池获取连接时是否检查连接有效性，true检查，false不检查
      testOnBorrow: true
      # 设置从连接池归还连接时是否检查连接有效性，true检查，false不检查
      testOnReturn: true
      # 可以支持PSCache（提升写入、查询效率）
      poolPreparedStatements: true
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 保持长连接
      keepAlive: true
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      web-stat-filter:
        # 是否启用StatFilter默认值true
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤的格式
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico
      stat-view-servlet:
        # 是否启用StatViewServlet默认值true
        enabled: true
        # 访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        # 是否能够重置数据
        reset-enable: false
        # 需要账号密码才能访问控制台，默认为root
        login-username: druid
        login-password: druid
        # IP白名单
        allow: 127.0.0.1
        # IP黑名单（共同存在时，deny优先于allow）
        deny:
  data:
    redis:
      host: ENC(lEiftW8SueOA9rXUyLHS9kWuVbkKcIib9tZbtYcWIavxfp4whAXHZWjoe1lZdy16)
      port: 6379
      connect-timeout: 10000
logging:
  level:
    com:
      redisCache: debug
    root: debug
mybatis-plus:
  dbType: mysql
  mapper-locations: classpath:mapper/**/**.xml
  global-config:
    db-config:
      # 主键类型：雪花算法
      id-type: ASSIGN_ID
      # 逻辑删除
      logic-delete-field: hide
  configuration:
    # 开启缓存
    cache-enabled: true
    # 允许JDBC支持自动生成主键，需要驱动兼容
    use-generated-keys: true
    # 允许使用方法签名中的名称作为语句参数名称
    use-actual-param-name: true
    # 日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: CAT4J-AUTH-TOKEN
  # 操作频率 2个小时
  active-timeout: 7200
  jwt-secret-key: asdasdasifhueuiwyurfewbfjsdafjk
  is-read-cookie: false
  is-read-header: true
  is-read-body: false
jasypt:
  encryptor:
    password: MHXJHx94e433poAQ